### ISSUE TITLE
paths must be configured

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-csv#1]
I built the plugin, "installed" by copying csv.spc to ~/.steampipe/config, and boiled csv.spc down to this:

```
connection "csv" {
  plugin = "csv"

  paths = [ "~/csv/*" ]
```

When I reach for .inspect in the cli it thinks no paths are configured. There are csv files in ~/csv.

What am I missing?

**Comment by e-gineer** [comment]
I think the `~` is the problem ... suspect we need to expand the home dir. Funny enough, @RyanJarv opened a pull request for this in the GCP plugin today - https://github.com/turbot/steampipe-plugin-gcp/pull/312/files

For now, please try again with a fully qualified path.

**Comment by judell** [comment]
That was it. I thought I had tried `/home/jon` as well, but evidently not, it does indeed work.

This is awesome stuff.
