### ISSUE TITLE
Partial Case-Sensivity makes CAMELCase.csv fail

### ISSUE THREAD

**Issue by pniederlag** [turbot/steampipe-plugin-csv#20]
**Describe the bug**
I have a CAMELCase.csv file on a case-sensivtive file-system

**Steampipe version (`steampipe -v`)**
Example: v0.14.3

**Plugin version (`steampipe plugin list`)**
csv@latest       | 0.3.0   | csv 

**To reproduce**

create a simple .csv file with some UPPERlower.csv name

.inspect does work, however using select always bails with relation does not exist

```
> .inspect csv.FIxme
+--------+-------+-------------------------------------------------------+
| column | type  | description                                           |
+--------+-------+-------------------------------------------------------+
| _ctx   | jsonb | Steampipe context in JSON form, e.g. connection_name. |
| one    | text  | Field 0.                                              |
| two    | text  | Field 1.                                              |
+--------+-------+-------------------------------------------------------+
> select * from FIxme
Error: relation "fixme" does not exist (SQLSTATE 42P01)
```

**Expected behavior**
the query should work

**Additional context**

renaming the file to alllowercase.csv works

**Comment by pniederlag** [comment]
@e-gineer how come I didn't even try this myself? Big thx for your instant feedback. Of course you are right.. quoting "FIxme" as well as "FIieldname" does the trick quite right.

thx for your efforts on clearifying docs

**Comment by pniederlag** [comment]
from my point of view this ticket could be closed

**Comment by cbruno10** [comment]
Thanks @pniederlag for confirming the quotes work! We're tracking the doc updates in https://github.com/turbot/steampipe-plugin-csv/issues/21, so if you have anymore questions or feedback, please feel free to comment in that issue as well.
