### ISSUE TITLE
Enable CSV plugin to access files stored in an S3 bucket

### ISSUE THREAD

**Issue by michaelgraff** [turbot/steampipe-plugin-csv#37]
**Describe the solution you'd like**
I absolutely love the power of the CSV plugin but it would be great if you could use this plugin to access files stored in an S3 bucket.   I currently get various reports delivered to S3 buckets and I'd love to be able to perform joins of the data stored in these CSV files with live data from the AWS plugin.  This would a) eliminate the extra step required to download files to my local machine for access via the CSV plugin and b) enable interesting use cases where CSV files could be leveraged to build dashboards on an server running in AWS and/or in Steampipe cloud.

the way I'd envision this working is you could configure your csv.spc to point to an S3 URL or ARN, and the credentials steampipe is using would need to be granted access to the bucket.

**Comment by cbruno10** [comment]
Hey @michaelgraff , we're actually working on adding a new capability to the Steampipe SDK to use [go-getter](https://github.com/hashicorp/go-getter) in https://github.com/turbot/steampipe-plugin-sdk/pull/439, which is still undergoing some changes and review.

With this feature, you'll be able to add [S3 bucket URLs](https://github.com/hashicorp/go-getter#s3-s3) into the `paths` config arg, and then the CSV plugin will render these.

I'll update this issue again once the new version is released, but if you have any questions in the meantime, please let us know!
