### ISSUE TITLE
Poor error message when the folder contains bad CSVs

### ISSUE THREAD

**Issue by pskrbasu** [turbot/steampipe-plugin-csv#4]
**Describe the bug**
When the paths in the connection config point to a folder that contains one/more invalid/bad CSV files, the plugin returns the following error:
```
failed to plugin initialise plugin 'steampipe-plugin-csv': TableMapFunc 'PluginTables' had unhandled error: parse error on line 1, column 25: bare " in non-quoted-field
```
It is hard to understand what's actually wrong from this message IMO.

**Steampipe version (`steampipe -v`)**
Example: v0.9.0-rc.0

**Plugin version (`steampipe plugin list`)**
Example: v0.3.0

**To reproduce**
Add a bad CSV file(may contain a bare " somewhere ) to a folder, and add the path to the folder in the connection config.
Query a good CSV.

**Expected behavior**

**Additional context**

**Comment by binaek** [comment]
Happens with me as well.

Attaching CSV which are crashing the plugin
[sample.csv](https://github.com/turbot/steampipe-plugin-csv/files/7604127/sample.csv)

Happens with empty CSV files as well - but github won't let me upload empty files :-(
