### ISSUE TITLE
byte order mark becomes space before first field in header when exporting from excel

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-csv#5]
I think that's what's happening, anyway. When saving a sheet as CSV from Excel, my default is UTF-8. and if the first column header is "name" it becomes " name" in the schema. 

My workaround: Save as CSV (MS-DOS). 😱

**Comment by rajlearner17** [comment]
@judell Thanks for the feedback. We will check this out.

**Comment by rajlearner17** [comment]
@judell I exported one of the google worksheets to CSV, could not replicate the same. Did you try with any MS Excel files?  That might be causing the issue? I can give it a try from a windows PC / apple-store MS excel may be.
